server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://PAYMENT-HYSTRIX-PROVIDER
          predicates:
            - Path=/payment/hystrix/ok/**   #断言,路径相匹配的进行路由
            - After=2020-05-30T10:59:34.102+08:00[Asia/Shanghai]    #在5/30后才能访问，时间生成规则？
            #- Cookie=username,zhangsan #并且Cookie是username=zhangsan才能访问

        - id: payment_routh2
          uri: lb://PAYMENT-HYSTRIX-PROVIDER
          predicates:
            - Path=/payment/hystrix/timeout/**   #断言,路径相匹配的进行路由

        - id: payment_routh3
          uri: lb://PAYMENT-HYSTRIX-PROVIDER
          predicates:
            - Path=/payment/circuit/**   #断言,路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7001.com:7001/eureka